/**
 * Copyright (c) 2022 bg117
 *
 * This software is released under the MIT License.
 * https://opensource.org/licenses/MIT
 */

#include <int/idt.h>
#include <int/interrupt_info.h>
#include <int/isr.h>

// auto-generated
#pragma region ISR stubs
extern void __attribute__((cdecl)) __isr_stub_0(void);
extern void __attribute__((cdecl)) __isr_stub_1(void);
extern void __attribute__((cdecl)) __isr_stub_2(void);
extern void __attribute__((cdecl)) __isr_stub_3(void);
extern void __attribute__((cdecl)) __isr_stub_4(void);
extern void __attribute__((cdecl)) __isr_stub_5(void);
extern void __attribute__((cdecl)) __isr_stub_6(void);
extern void __attribute__((cdecl)) __isr_stub_7(void);
extern void __attribute__((cdecl)) __isr_stub_8(void);
extern void __attribute__((cdecl)) __isr_stub_9(void);
extern void __attribute__((cdecl)) __isr_stub_10(void);
extern void __attribute__((cdecl)) __isr_stub_11(void);
extern void __attribute__((cdecl)) __isr_stub_12(void);
extern void __attribute__((cdecl)) __isr_stub_13(void);
extern void __attribute__((cdecl)) __isr_stub_14(void);
extern void __attribute__((cdecl)) __isr_stub_15(void);
extern void __attribute__((cdecl)) __isr_stub_16(void);
extern void __attribute__((cdecl)) __isr_stub_17(void);
extern void __attribute__((cdecl)) __isr_stub_18(void);
extern void __attribute__((cdecl)) __isr_stub_19(void);
extern void __attribute__((cdecl)) __isr_stub_20(void);
extern void __attribute__((cdecl)) __isr_stub_21(void);
extern void __attribute__((cdecl)) __isr_stub_22(void);
extern void __attribute__((cdecl)) __isr_stub_23(void);
extern void __attribute__((cdecl)) __isr_stub_24(void);
extern void __attribute__((cdecl)) __isr_stub_25(void);
extern void __attribute__((cdecl)) __isr_stub_26(void);
extern void __attribute__((cdecl)) __isr_stub_27(void);
extern void __attribute__((cdecl)) __isr_stub_28(void);
extern void __attribute__((cdecl)) __isr_stub_29(void);
extern void __attribute__((cdecl)) __isr_stub_30(void);
extern void __attribute__((cdecl)) __isr_stub_31(void);
extern void __attribute__((cdecl)) __isr_stub_32(void);
extern void __attribute__((cdecl)) __isr_stub_33(void);
extern void __attribute__((cdecl)) __isr_stub_34(void);
extern void __attribute__((cdecl)) __isr_stub_35(void);
extern void __attribute__((cdecl)) __isr_stub_36(void);
extern void __attribute__((cdecl)) __isr_stub_37(void);
extern void __attribute__((cdecl)) __isr_stub_38(void);
extern void __attribute__((cdecl)) __isr_stub_39(void);
extern void __attribute__((cdecl)) __isr_stub_40(void);
extern void __attribute__((cdecl)) __isr_stub_41(void);
extern void __attribute__((cdecl)) __isr_stub_42(void);
extern void __attribute__((cdecl)) __isr_stub_43(void);
extern void __attribute__((cdecl)) __isr_stub_44(void);
extern void __attribute__((cdecl)) __isr_stub_45(void);
extern void __attribute__((cdecl)) __isr_stub_46(void);
extern void __attribute__((cdecl)) __isr_stub_47(void);
extern void __attribute__((cdecl)) __isr_stub_48(void);
extern void __attribute__((cdecl)) __isr_stub_49(void);
extern void __attribute__((cdecl)) __isr_stub_50(void);
extern void __attribute__((cdecl)) __isr_stub_51(void);
extern void __attribute__((cdecl)) __isr_stub_52(void);
extern void __attribute__((cdecl)) __isr_stub_53(void);
extern void __attribute__((cdecl)) __isr_stub_54(void);
extern void __attribute__((cdecl)) __isr_stub_55(void);
extern void __attribute__((cdecl)) __isr_stub_56(void);
extern void __attribute__((cdecl)) __isr_stub_57(void);
extern void __attribute__((cdecl)) __isr_stub_58(void);
extern void __attribute__((cdecl)) __isr_stub_59(void);
extern void __attribute__((cdecl)) __isr_stub_60(void);
extern void __attribute__((cdecl)) __isr_stub_61(void);
extern void __attribute__((cdecl)) __isr_stub_62(void);
extern void __attribute__((cdecl)) __isr_stub_63(void);
extern void __attribute__((cdecl)) __isr_stub_64(void);
extern void __attribute__((cdecl)) __isr_stub_65(void);
extern void __attribute__((cdecl)) __isr_stub_66(void);
extern void __attribute__((cdecl)) __isr_stub_67(void);
extern void __attribute__((cdecl)) __isr_stub_68(void);
extern void __attribute__((cdecl)) __isr_stub_69(void);
extern void __attribute__((cdecl)) __isr_stub_70(void);
extern void __attribute__((cdecl)) __isr_stub_71(void);
extern void __attribute__((cdecl)) __isr_stub_72(void);
extern void __attribute__((cdecl)) __isr_stub_73(void);
extern void __attribute__((cdecl)) __isr_stub_74(void);
extern void __attribute__((cdecl)) __isr_stub_75(void);
extern void __attribute__((cdecl)) __isr_stub_76(void);
extern void __attribute__((cdecl)) __isr_stub_77(void);
extern void __attribute__((cdecl)) __isr_stub_78(void);
extern void __attribute__((cdecl)) __isr_stub_79(void);
extern void __attribute__((cdecl)) __isr_stub_80(void);
extern void __attribute__((cdecl)) __isr_stub_81(void);
extern void __attribute__((cdecl)) __isr_stub_82(void);
extern void __attribute__((cdecl)) __isr_stub_83(void);
extern void __attribute__((cdecl)) __isr_stub_84(void);
extern void __attribute__((cdecl)) __isr_stub_85(void);
extern void __attribute__((cdecl)) __isr_stub_86(void);
extern void __attribute__((cdecl)) __isr_stub_87(void);
extern void __attribute__((cdecl)) __isr_stub_88(void);
extern void __attribute__((cdecl)) __isr_stub_89(void);
extern void __attribute__((cdecl)) __isr_stub_90(void);
extern void __attribute__((cdecl)) __isr_stub_91(void);
extern void __attribute__((cdecl)) __isr_stub_92(void);
extern void __attribute__((cdecl)) __isr_stub_93(void);
extern void __attribute__((cdecl)) __isr_stub_94(void);
extern void __attribute__((cdecl)) __isr_stub_95(void);
extern void __attribute__((cdecl)) __isr_stub_96(void);
extern void __attribute__((cdecl)) __isr_stub_97(void);
extern void __attribute__((cdecl)) __isr_stub_98(void);
extern void __attribute__((cdecl)) __isr_stub_99(void);
extern void __attribute__((cdecl)) __isr_stub_100(void);
extern void __attribute__((cdecl)) __isr_stub_101(void);
extern void __attribute__((cdecl)) __isr_stub_102(void);
extern void __attribute__((cdecl)) __isr_stub_103(void);
extern void __attribute__((cdecl)) __isr_stub_104(void);
extern void __attribute__((cdecl)) __isr_stub_105(void);
extern void __attribute__((cdecl)) __isr_stub_106(void);
extern void __attribute__((cdecl)) __isr_stub_107(void);
extern void __attribute__((cdecl)) __isr_stub_108(void);
extern void __attribute__((cdecl)) __isr_stub_109(void);
extern void __attribute__((cdecl)) __isr_stub_110(void);
extern void __attribute__((cdecl)) __isr_stub_111(void);
extern void __attribute__((cdecl)) __isr_stub_112(void);
extern void __attribute__((cdecl)) __isr_stub_113(void);
extern void __attribute__((cdecl)) __isr_stub_114(void);
extern void __attribute__((cdecl)) __isr_stub_115(void);
extern void __attribute__((cdecl)) __isr_stub_116(void);
extern void __attribute__((cdecl)) __isr_stub_117(void);
extern void __attribute__((cdecl)) __isr_stub_118(void);
extern void __attribute__((cdecl)) __isr_stub_119(void);
extern void __attribute__((cdecl)) __isr_stub_120(void);
extern void __attribute__((cdecl)) __isr_stub_121(void);
extern void __attribute__((cdecl)) __isr_stub_122(void);
extern void __attribute__((cdecl)) __isr_stub_123(void);
extern void __attribute__((cdecl)) __isr_stub_124(void);
extern void __attribute__((cdecl)) __isr_stub_125(void);
extern void __attribute__((cdecl)) __isr_stub_126(void);
extern void __attribute__((cdecl)) __isr_stub_127(void);
extern void __attribute__((cdecl)) __isr_stub_128(void);
extern void __attribute__((cdecl)) __isr_stub_129(void);
extern void __attribute__((cdecl)) __isr_stub_130(void);
extern void __attribute__((cdecl)) __isr_stub_131(void);
extern void __attribute__((cdecl)) __isr_stub_132(void);
extern void __attribute__((cdecl)) __isr_stub_133(void);
extern void __attribute__((cdecl)) __isr_stub_134(void);
extern void __attribute__((cdecl)) __isr_stub_135(void);
extern void __attribute__((cdecl)) __isr_stub_136(void);
extern void __attribute__((cdecl)) __isr_stub_137(void);
extern void __attribute__((cdecl)) __isr_stub_138(void);
extern void __attribute__((cdecl)) __isr_stub_139(void);
extern void __attribute__((cdecl)) __isr_stub_140(void);
extern void __attribute__((cdecl)) __isr_stub_141(void);
extern void __attribute__((cdecl)) __isr_stub_142(void);
extern void __attribute__((cdecl)) __isr_stub_143(void);
extern void __attribute__((cdecl)) __isr_stub_144(void);
extern void __attribute__((cdecl)) __isr_stub_145(void);
extern void __attribute__((cdecl)) __isr_stub_146(void);
extern void __attribute__((cdecl)) __isr_stub_147(void);
extern void __attribute__((cdecl)) __isr_stub_148(void);
extern void __attribute__((cdecl)) __isr_stub_149(void);
extern void __attribute__((cdecl)) __isr_stub_150(void);
extern void __attribute__((cdecl)) __isr_stub_151(void);
extern void __attribute__((cdecl)) __isr_stub_152(void);
extern void __attribute__((cdecl)) __isr_stub_153(void);
extern void __attribute__((cdecl)) __isr_stub_154(void);
extern void __attribute__((cdecl)) __isr_stub_155(void);
extern void __attribute__((cdecl)) __isr_stub_156(void);
extern void __attribute__((cdecl)) __isr_stub_157(void);
extern void __attribute__((cdecl)) __isr_stub_158(void);
extern void __attribute__((cdecl)) __isr_stub_159(void);
extern void __attribute__((cdecl)) __isr_stub_160(void);
extern void __attribute__((cdecl)) __isr_stub_161(void);
extern void __attribute__((cdecl)) __isr_stub_162(void);
extern void __attribute__((cdecl)) __isr_stub_163(void);
extern void __attribute__((cdecl)) __isr_stub_164(void);
extern void __attribute__((cdecl)) __isr_stub_165(void);
extern void __attribute__((cdecl)) __isr_stub_166(void);
extern void __attribute__((cdecl)) __isr_stub_167(void);
extern void __attribute__((cdecl)) __isr_stub_168(void);
extern void __attribute__((cdecl)) __isr_stub_169(void);
extern void __attribute__((cdecl)) __isr_stub_170(void);
extern void __attribute__((cdecl)) __isr_stub_171(void);
extern void __attribute__((cdecl)) __isr_stub_172(void);
extern void __attribute__((cdecl)) __isr_stub_173(void);
extern void __attribute__((cdecl)) __isr_stub_174(void);
extern void __attribute__((cdecl)) __isr_stub_175(void);
extern void __attribute__((cdecl)) __isr_stub_176(void);
extern void __attribute__((cdecl)) __isr_stub_177(void);
extern void __attribute__((cdecl)) __isr_stub_178(void);
extern void __attribute__((cdecl)) __isr_stub_179(void);
extern void __attribute__((cdecl)) __isr_stub_180(void);
extern void __attribute__((cdecl)) __isr_stub_181(void);
extern void __attribute__((cdecl)) __isr_stub_182(void);
extern void __attribute__((cdecl)) __isr_stub_183(void);
extern void __attribute__((cdecl)) __isr_stub_184(void);
extern void __attribute__((cdecl)) __isr_stub_185(void);
extern void __attribute__((cdecl)) __isr_stub_186(void);
extern void __attribute__((cdecl)) __isr_stub_187(void);
extern void __attribute__((cdecl)) __isr_stub_188(void);
extern void __attribute__((cdecl)) __isr_stub_189(void);
extern void __attribute__((cdecl)) __isr_stub_190(void);
extern void __attribute__((cdecl)) __isr_stub_191(void);
extern void __attribute__((cdecl)) __isr_stub_192(void);
extern void __attribute__((cdecl)) __isr_stub_193(void);
extern void __attribute__((cdecl)) __isr_stub_194(void);
extern void __attribute__((cdecl)) __isr_stub_195(void);
extern void __attribute__((cdecl)) __isr_stub_196(void);
extern void __attribute__((cdecl)) __isr_stub_197(void);
extern void __attribute__((cdecl)) __isr_stub_198(void);
extern void __attribute__((cdecl)) __isr_stub_199(void);
extern void __attribute__((cdecl)) __isr_stub_200(void);
extern void __attribute__((cdecl)) __isr_stub_201(void);
extern void __attribute__((cdecl)) __isr_stub_202(void);
extern void __attribute__((cdecl)) __isr_stub_203(void);
extern void __attribute__((cdecl)) __isr_stub_204(void);
extern void __attribute__((cdecl)) __isr_stub_205(void);
extern void __attribute__((cdecl)) __isr_stub_206(void);
extern void __attribute__((cdecl)) __isr_stub_207(void);
extern void __attribute__((cdecl)) __isr_stub_208(void);
extern void __attribute__((cdecl)) __isr_stub_209(void);
extern void __attribute__((cdecl)) __isr_stub_210(void);
extern void __attribute__((cdecl)) __isr_stub_211(void);
extern void __attribute__((cdecl)) __isr_stub_212(void);
extern void __attribute__((cdecl)) __isr_stub_213(void);
extern void __attribute__((cdecl)) __isr_stub_214(void);
extern void __attribute__((cdecl)) __isr_stub_215(void);
extern void __attribute__((cdecl)) __isr_stub_216(void);
extern void __attribute__((cdecl)) __isr_stub_217(void);
extern void __attribute__((cdecl)) __isr_stub_218(void);
extern void __attribute__((cdecl)) __isr_stub_219(void);
extern void __attribute__((cdecl)) __isr_stub_220(void);
extern void __attribute__((cdecl)) __isr_stub_221(void);
extern void __attribute__((cdecl)) __isr_stub_222(void);
extern void __attribute__((cdecl)) __isr_stub_223(void);
extern void __attribute__((cdecl)) __isr_stub_224(void);
extern void __attribute__((cdecl)) __isr_stub_225(void);
extern void __attribute__((cdecl)) __isr_stub_226(void);
extern void __attribute__((cdecl)) __isr_stub_227(void);
extern void __attribute__((cdecl)) __isr_stub_228(void);
extern void __attribute__((cdecl)) __isr_stub_229(void);
extern void __attribute__((cdecl)) __isr_stub_230(void);
extern void __attribute__((cdecl)) __isr_stub_231(void);
extern void __attribute__((cdecl)) __isr_stub_232(void);
extern void __attribute__((cdecl)) __isr_stub_233(void);
extern void __attribute__((cdecl)) __isr_stub_234(void);
extern void __attribute__((cdecl)) __isr_stub_235(void);
extern void __attribute__((cdecl)) __isr_stub_236(void);
extern void __attribute__((cdecl)) __isr_stub_237(void);
extern void __attribute__((cdecl)) __isr_stub_238(void);
extern void __attribute__((cdecl)) __isr_stub_239(void);
extern void __attribute__((cdecl)) __isr_stub_240(void);
extern void __attribute__((cdecl)) __isr_stub_241(void);
extern void __attribute__((cdecl)) __isr_stub_242(void);
extern void __attribute__((cdecl)) __isr_stub_243(void);
extern void __attribute__((cdecl)) __isr_stub_244(void);
extern void __attribute__((cdecl)) __isr_stub_245(void);
extern void __attribute__((cdecl)) __isr_stub_246(void);
extern void __attribute__((cdecl)) __isr_stub_247(void);
extern void __attribute__((cdecl)) __isr_stub_248(void);
extern void __attribute__((cdecl)) __isr_stub_249(void);
extern void __attribute__((cdecl)) __isr_stub_250(void);
extern void __attribute__((cdecl)) __isr_stub_251(void);
extern void __attribute__((cdecl)) __isr_stub_252(void);
extern void __attribute__((cdecl)) __isr_stub_253(void);
extern void __attribute__((cdecl)) __isr_stub_254(void);
extern void __attribute__((cdecl)) __isr_stub_255(void);
#pragma endregion

// low-level ISR dispatcher
void __dispatch_exception(InterruptInfo *info);

static void init_idt(uint8_t code_offset);

static IdtEntry      g_idt[256] = { 0 };
static IdtDescriptor g_idt_descriptor;

// the actual interrupt service routines
static void (*g_isrs[256])(InterruptInfo *) = { 0 };

void isr_init(uint8_t code_offset)
{
    init_idt(code_offset);
}

void isr_load_idt(void)
{
    idt_descriptor_init(&g_idt_descriptor, g_idt, sizeof g_idt / sizeof g_idt[0]);
    idt_descriptor_load(&g_idt_descriptor);
}

void isr_map_interrupt_handler(uint8_t vector, void (*handler)(InterruptInfo *))
{
    g_isrs[vector] = handler;
}

void __dispatch_exception(InterruptInfo *info)
{
    void (*handler)(InterruptInfo *) = g_isrs[info->vector];
    if (handler)
        handler(info);
}

void init_idt(uint8_t code_offset)
{
    // oh, and, before you ask, this part was generated by a shell for-loop
    // ;)
#pragma region ISR initialization
    g_idt[0]   = idt_make_entry(__isr_stub_0, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[1]   = idt_make_entry(__isr_stub_1, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[2]   = idt_make_entry(__isr_stub_2, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[3]   = idt_make_entry(__isr_stub_3, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[4]   = idt_make_entry(__isr_stub_4, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[5]   = idt_make_entry(__isr_stub_5, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[6]   = idt_make_entry(__isr_stub_6, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[7]   = idt_make_entry(__isr_stub_7, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[8]   = idt_make_entry(__isr_stub_8, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[9]   = idt_make_entry(__isr_stub_9, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[10]  = idt_make_entry(__isr_stub_10, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[11]  = idt_make_entry(__isr_stub_11, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[12]  = idt_make_entry(__isr_stub_12, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[13]  = idt_make_entry(__isr_stub_13, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[14]  = idt_make_entry(__isr_stub_14, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[15]  = idt_make_entry(__isr_stub_15, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[16]  = idt_make_entry(__isr_stub_16, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[17]  = idt_make_entry(__isr_stub_17, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[18]  = idt_make_entry(__isr_stub_18, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[19]  = idt_make_entry(__isr_stub_19, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[20]  = idt_make_entry(__isr_stub_20, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[21]  = idt_make_entry(__isr_stub_21, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[22]  = idt_make_entry(__isr_stub_22, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[23]  = idt_make_entry(__isr_stub_23, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[24]  = idt_make_entry(__isr_stub_24, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[25]  = idt_make_entry(__isr_stub_25, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[26]  = idt_make_entry(__isr_stub_26, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[27]  = idt_make_entry(__isr_stub_27, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[28]  = idt_make_entry(__isr_stub_28, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[29]  = idt_make_entry(__isr_stub_29, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[30]  = idt_make_entry(__isr_stub_30, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[31]  = idt_make_entry(__isr_stub_31, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[32]  = idt_make_entry(__isr_stub_32, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[33]  = idt_make_entry(__isr_stub_33, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[34]  = idt_make_entry(__isr_stub_34, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[35]  = idt_make_entry(__isr_stub_35, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[36]  = idt_make_entry(__isr_stub_36, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[37]  = idt_make_entry(__isr_stub_37, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[38]  = idt_make_entry(__isr_stub_38, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[39]  = idt_make_entry(__isr_stub_39, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[40]  = idt_make_entry(__isr_stub_40, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[41]  = idt_make_entry(__isr_stub_41, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[42]  = idt_make_entry(__isr_stub_42, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[43]  = idt_make_entry(__isr_stub_43, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[44]  = idt_make_entry(__isr_stub_44, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[45]  = idt_make_entry(__isr_stub_45, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[46]  = idt_make_entry(__isr_stub_46, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[47]  = idt_make_entry(__isr_stub_47, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[48]  = idt_make_entry(__isr_stub_48, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[49]  = idt_make_entry(__isr_stub_49, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[50]  = idt_make_entry(__isr_stub_50, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[51]  = idt_make_entry(__isr_stub_51, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[52]  = idt_make_entry(__isr_stub_52, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[53]  = idt_make_entry(__isr_stub_53, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[54]  = idt_make_entry(__isr_stub_54, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[55]  = idt_make_entry(__isr_stub_55, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[56]  = idt_make_entry(__isr_stub_56, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[57]  = idt_make_entry(__isr_stub_57, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[58]  = idt_make_entry(__isr_stub_58, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[59]  = idt_make_entry(__isr_stub_59, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[60]  = idt_make_entry(__isr_stub_60, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[61]  = idt_make_entry(__isr_stub_61, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[62]  = idt_make_entry(__isr_stub_62, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[63]  = idt_make_entry(__isr_stub_63, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[64]  = idt_make_entry(__isr_stub_64, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[65]  = idt_make_entry(__isr_stub_65, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[66]  = idt_make_entry(__isr_stub_66, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[67]  = idt_make_entry(__isr_stub_67, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[68]  = idt_make_entry(__isr_stub_68, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[69]  = idt_make_entry(__isr_stub_69, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[70]  = idt_make_entry(__isr_stub_70, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[71]  = idt_make_entry(__isr_stub_71, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[72]  = idt_make_entry(__isr_stub_72, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[73]  = idt_make_entry(__isr_stub_73, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[74]  = idt_make_entry(__isr_stub_74, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[75]  = idt_make_entry(__isr_stub_75, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[76]  = idt_make_entry(__isr_stub_76, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[77]  = idt_make_entry(__isr_stub_77, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[78]  = idt_make_entry(__isr_stub_78, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[79]  = idt_make_entry(__isr_stub_79, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[80]  = idt_make_entry(__isr_stub_80, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[81]  = idt_make_entry(__isr_stub_81, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[82]  = idt_make_entry(__isr_stub_82, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[83]  = idt_make_entry(__isr_stub_83, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[84]  = idt_make_entry(__isr_stub_84, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[85]  = idt_make_entry(__isr_stub_85, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[86]  = idt_make_entry(__isr_stub_86, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[87]  = idt_make_entry(__isr_stub_87, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[88]  = idt_make_entry(__isr_stub_88, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[89]  = idt_make_entry(__isr_stub_89, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[90]  = idt_make_entry(__isr_stub_90, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[91]  = idt_make_entry(__isr_stub_91, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[92]  = idt_make_entry(__isr_stub_92, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[93]  = idt_make_entry(__isr_stub_93, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[94]  = idt_make_entry(__isr_stub_94, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[95]  = idt_make_entry(__isr_stub_95, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[96]  = idt_make_entry(__isr_stub_96, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[97]  = idt_make_entry(__isr_stub_97, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[98]  = idt_make_entry(__isr_stub_98, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[99]  = idt_make_entry(__isr_stub_99, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[100] = idt_make_entry(__isr_stub_100, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[101] = idt_make_entry(__isr_stub_101, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[102] = idt_make_entry(__isr_stub_102, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[103] = idt_make_entry(__isr_stub_103, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[104] = idt_make_entry(__isr_stub_104, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[105] = idt_make_entry(__isr_stub_105, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[106] = idt_make_entry(__isr_stub_106, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[107] = idt_make_entry(__isr_stub_107, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[108] = idt_make_entry(__isr_stub_108, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[109] = idt_make_entry(__isr_stub_109, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[110] = idt_make_entry(__isr_stub_110, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[111] = idt_make_entry(__isr_stub_111, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[112] = idt_make_entry(__isr_stub_112, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[113] = idt_make_entry(__isr_stub_113, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[114] = idt_make_entry(__isr_stub_114, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[115] = idt_make_entry(__isr_stub_115, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[116] = idt_make_entry(__isr_stub_116, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[117] = idt_make_entry(__isr_stub_117, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[118] = idt_make_entry(__isr_stub_118, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[119] = idt_make_entry(__isr_stub_119, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[120] = idt_make_entry(__isr_stub_120, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[121] = idt_make_entry(__isr_stub_121, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[122] = idt_make_entry(__isr_stub_122, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[123] = idt_make_entry(__isr_stub_123, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[124] = idt_make_entry(__isr_stub_124, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[125] = idt_make_entry(__isr_stub_125, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[126] = idt_make_entry(__isr_stub_126, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[127] = idt_make_entry(__isr_stub_127, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[128] = idt_make_entry(__isr_stub_128, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[129] = idt_make_entry(__isr_stub_129, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[130] = idt_make_entry(__isr_stub_130, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[131] = idt_make_entry(__isr_stub_131, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[132] = idt_make_entry(__isr_stub_132, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[133] = idt_make_entry(__isr_stub_133, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[134] = idt_make_entry(__isr_stub_134, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[135] = idt_make_entry(__isr_stub_135, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[136] = idt_make_entry(__isr_stub_136, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[137] = idt_make_entry(__isr_stub_137, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[138] = idt_make_entry(__isr_stub_138, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[139] = idt_make_entry(__isr_stub_139, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[140] = idt_make_entry(__isr_stub_140, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[141] = idt_make_entry(__isr_stub_141, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[142] = idt_make_entry(__isr_stub_142, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[143] = idt_make_entry(__isr_stub_143, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[144] = idt_make_entry(__isr_stub_144, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[145] = idt_make_entry(__isr_stub_145, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[146] = idt_make_entry(__isr_stub_146, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[147] = idt_make_entry(__isr_stub_147, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[148] = idt_make_entry(__isr_stub_148, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[149] = idt_make_entry(__isr_stub_149, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[150] = idt_make_entry(__isr_stub_150, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[151] = idt_make_entry(__isr_stub_151, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[152] = idt_make_entry(__isr_stub_152, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[153] = idt_make_entry(__isr_stub_153, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[154] = idt_make_entry(__isr_stub_154, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[155] = idt_make_entry(__isr_stub_155, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[156] = idt_make_entry(__isr_stub_156, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[157] = idt_make_entry(__isr_stub_157, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[158] = idt_make_entry(__isr_stub_158, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[159] = idt_make_entry(__isr_stub_159, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[160] = idt_make_entry(__isr_stub_160, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[161] = idt_make_entry(__isr_stub_161, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[162] = idt_make_entry(__isr_stub_162, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[163] = idt_make_entry(__isr_stub_163, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[164] = idt_make_entry(__isr_stub_164, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[165] = idt_make_entry(__isr_stub_165, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[166] = idt_make_entry(__isr_stub_166, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[167] = idt_make_entry(__isr_stub_167, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[168] = idt_make_entry(__isr_stub_168, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[169] = idt_make_entry(__isr_stub_169, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[170] = idt_make_entry(__isr_stub_170, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[171] = idt_make_entry(__isr_stub_171, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[172] = idt_make_entry(__isr_stub_172, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[173] = idt_make_entry(__isr_stub_173, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[174] = idt_make_entry(__isr_stub_174, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[175] = idt_make_entry(__isr_stub_175, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[176] = idt_make_entry(__isr_stub_176, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[177] = idt_make_entry(__isr_stub_177, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[178] = idt_make_entry(__isr_stub_178, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[179] = idt_make_entry(__isr_stub_179, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[180] = idt_make_entry(__isr_stub_180, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[181] = idt_make_entry(__isr_stub_181, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[182] = idt_make_entry(__isr_stub_182, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[183] = idt_make_entry(__isr_stub_183, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[184] = idt_make_entry(__isr_stub_184, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[185] = idt_make_entry(__isr_stub_185, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[186] = idt_make_entry(__isr_stub_186, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[187] = idt_make_entry(__isr_stub_187, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[188] = idt_make_entry(__isr_stub_188, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[189] = idt_make_entry(__isr_stub_189, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[190] = idt_make_entry(__isr_stub_190, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[191] = idt_make_entry(__isr_stub_191, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[192] = idt_make_entry(__isr_stub_192, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[193] = idt_make_entry(__isr_stub_193, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[194] = idt_make_entry(__isr_stub_194, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[195] = idt_make_entry(__isr_stub_195, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[196] = idt_make_entry(__isr_stub_196, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[197] = idt_make_entry(__isr_stub_197, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[198] = idt_make_entry(__isr_stub_198, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[199] = idt_make_entry(__isr_stub_199, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[200] = idt_make_entry(__isr_stub_200, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[201] = idt_make_entry(__isr_stub_201, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[202] = idt_make_entry(__isr_stub_202, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[203] = idt_make_entry(__isr_stub_203, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[204] = idt_make_entry(__isr_stub_204, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[205] = idt_make_entry(__isr_stub_205, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[206] = idt_make_entry(__isr_stub_206, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[207] = idt_make_entry(__isr_stub_207, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[208] = idt_make_entry(__isr_stub_208, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[209] = idt_make_entry(__isr_stub_209, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[210] = idt_make_entry(__isr_stub_210, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[211] = idt_make_entry(__isr_stub_211, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[212] = idt_make_entry(__isr_stub_212, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[213] = idt_make_entry(__isr_stub_213, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[214] = idt_make_entry(__isr_stub_214, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[215] = idt_make_entry(__isr_stub_215, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[216] = idt_make_entry(__isr_stub_216, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[217] = idt_make_entry(__isr_stub_217, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[218] = idt_make_entry(__isr_stub_218, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[219] = idt_make_entry(__isr_stub_219, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[220] = idt_make_entry(__isr_stub_220, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[221] = idt_make_entry(__isr_stub_221, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[222] = idt_make_entry(__isr_stub_222, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[223] = idt_make_entry(__isr_stub_223, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[224] = idt_make_entry(__isr_stub_224, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[225] = idt_make_entry(__isr_stub_225, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[226] = idt_make_entry(__isr_stub_226, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[227] = idt_make_entry(__isr_stub_227, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[228] = idt_make_entry(__isr_stub_228, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[229] = idt_make_entry(__isr_stub_229, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[230] = idt_make_entry(__isr_stub_230, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[231] = idt_make_entry(__isr_stub_231, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[232] = idt_make_entry(__isr_stub_232, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[233] = idt_make_entry(__isr_stub_233, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[234] = idt_make_entry(__isr_stub_234, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[235] = idt_make_entry(__isr_stub_235, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[236] = idt_make_entry(__isr_stub_236, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[237] = idt_make_entry(__isr_stub_237, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[238] = idt_make_entry(__isr_stub_238, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[239] = idt_make_entry(__isr_stub_239, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[240] = idt_make_entry(__isr_stub_240, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[241] = idt_make_entry(__isr_stub_241, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[242] = idt_make_entry(__isr_stub_242, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[243] = idt_make_entry(__isr_stub_243, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[244] = idt_make_entry(__isr_stub_244, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[245] = idt_make_entry(__isr_stub_245, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[246] = idt_make_entry(__isr_stub_246, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[247] = idt_make_entry(__isr_stub_247, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[248] = idt_make_entry(__isr_stub_248, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[249] = idt_make_entry(__isr_stub_249, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[250] = idt_make_entry(__isr_stub_250, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[251] = idt_make_entry(__isr_stub_251, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[252] = idt_make_entry(__isr_stub_252, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[253] = idt_make_entry(__isr_stub_253, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[254] = idt_make_entry(__isr_stub_254, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
    g_idt[255] = idt_make_entry(__isr_stub_255, code_offset, IDT_AX_RING0 | IDT_AX_I386_INT | IDT_AX_PRESENT);
#pragma endregion
}
